FROM ubuntu:latest
LABEL maintainer="Linux kernel travel"

RUN set -ex; \
  apt-get update -y; \
  DEBIAN_FRONTEND=noninteractive \
  apt install -y bison build-essential cmake flex git libedit-dev  libllvm11 llvm-11-dev libclang-11-dev python zlib1g-dev libelf-dev libfl-dev python3-distutils

COPY installbcc.sh /
RUN set -ex; \
  chmod +x /installbcc.sh; \
  /bin/bash ./installbcc.sh

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
